# Generated by Django 2.2.1 on 2019-06-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='LanguageModel',
        ),
    ]
