# Generated by Django 2.2.1 on 2019-06-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20190601_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageModel',
        ),
    ]
